# Generated by Django 2.0 on 2019-05-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ps', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=20)),
                ('contents', models.CharField(max_length=900)),
                ('lasttime', models.DateTimeField(auto_now=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
